# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoldmarkLint < Formula
  desc "A Markdown linter written in Go using the goldmark parser"
  homepage "https://github.com/mrueg/goldmark-lint"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrueg/goldmark-lint/releases/download/v0.2.0/goldmark-lint_darwin_amd64.tar.gz"
      sha256 "b48f265827f4048336927e849c52746d0e7f77ec4bd730b5260feaeffd572c83"

      define_method(:install) do
        bin.install "goldmark-lint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrueg/goldmark-lint/releases/download/v0.2.0/goldmark-lint_darwin_arm64.tar.gz"
      sha256 "07900a0c6856f67265d2b7cee329e25a7ca441b30e5460d27c9481bcbaaf8128"

      define_method(:install) do
        bin.install "goldmark-lint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrueg/goldmark-lint/releases/download/v0.2.0/goldmark-lint_linux_amd64.tar.gz"
      sha256 "0245cc79e2879617354a10a6099c6e32930595362cc79abea1e60f59f0b2eb74"
      define_method(:install) do
        bin.install "goldmark-lint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrueg/goldmark-lint/releases/download/v0.2.0/goldmark-lint_linux_arm64.tar.gz"
      sha256 "1774d9fcf4b39ffe65f3d9ce2f622c794465bcf3718cad407f5ca7f7a6511ae2"
      define_method(:install) do
        bin.install "goldmark-lint"
      end
    end
  end
end
