# This file was generated by GoReleaser. DO NOT EDIT.
cask "goldmark-lint" do
  name "goldmark-lint"
  desc "A Markdown linter written in Go using the goldmark parser"
  homepage "https://github.com/mrueg/goldmark-lint"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goldmark-lint"

  on_macos do
    on_intel do
      url "https://github.com/mrueg/goldmark-lint/releases/download/v#{version}/goldmark-lint_darwin_amd64.tar.gz"
      sha256 "630c7cd1ab0f3ab83e83ec6f0db81650d097f14e1b34d9f6d5b2830d67158206"
    end
    on_arm do
      url "https://github.com/mrueg/goldmark-lint/releases/download/v#{version}/goldmark-lint_darwin_arm64.tar.gz"
      sha256 "3c47cfda999e1a93c4b45206e18a54b4b729fcc306fe1b21ba3b77dcdae56225"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mrueg/goldmark-lint/releases/download/v#{version}/goldmark-lint_linux_amd64.tar.gz"
      sha256 "c257c60a44c96cbc7d703648ade48354dbd5b244a2c56e5ec1fa7b840d411ac5"
    end
    on_arm do
      url "https://github.com/mrueg/goldmark-lint/releases/download/v#{version}/goldmark-lint_linux_arm64.tar.gz"
      sha256 "787ba42b94892c5ed8e795f1c22d7de0ef806aea6e2d0891c9c60fe842d18cda"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/goldmark-lint"]
    end
  end

  # No zap stanza required
end
