# This file was generated by GoReleaser. DO NOT EDIT.
cask "goldmark-lint" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "96bd5290fe7c6286a90249bcb0dd54c98e0cb0b6778990f7049ed29eb51af84a"
      url "https://github.com/mrueg/goldmark-lint/releases/download/v#{version}/goldmark-lint_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6e7b352ad3ed493e0e4e2a513f9cbe7f1c89b9d166c4a1396c08da9f58e18649"
      url "https://github.com/mrueg/goldmark-lint/releases/download/v#{version}/goldmark-lint_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7da630667c19ac815dae4400819bc3be11f2db6e4e611faaeb3838ede8df7dcd"
      url "https://github.com/mrueg/goldmark-lint/releases/download/v#{version}/goldmark-lint_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f42efb67a9247e128a312e96b0cb7adbe3497b9d2a622898f19010f491bd5e9e"
      url "https://github.com/mrueg/goldmark-lint/releases/download/v#{version}/goldmark-lint_linux_arm64.tar.gz"
    end
  end

  name "goldmark-lint"
  desc "A Markdown linter written in Go using the goldmark parser"
  homepage "https://github.com/mrueg/goldmark-lint"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goldmark-lint"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/goldmark-lint"]
    end
  end

  # No zap stanza required

end
