# This file was generated by GoReleaser. DO NOT EDIT.
cask "goldmark-lint" do
  name "goldmark-lint"
  desc "A Markdown linter written in Go using the goldmark parser"
  homepage "https://github.com/mrueg/goldmark-lint"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goldmark-lint"

  on_macos do
    on_intel do
      url "https://github.com/mrueg/goldmark-lint/releases/download/v#{version}/goldmark-lint_darwin_amd64.tar.gz"
      sha256 "9f65ca22b96298b48a8769960238a57349299c0f012615dcfe5a12b129bfcb2a"
    end
    on_arm do
      url "https://github.com/mrueg/goldmark-lint/releases/download/v#{version}/goldmark-lint_darwin_arm64.tar.gz"
      sha256 "7c8124f940982da831e8315dea3fda710390e6ec9bd92d79900d0772409baefb"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mrueg/goldmark-lint/releases/download/v#{version}/goldmark-lint_linux_amd64.tar.gz"
      sha256 "41ad4b9f1947e98ac095e7e3c54727d8f484d51782a7aae9ad4e9b09a6c1d4af"
    end
    on_arm do
      url "https://github.com/mrueg/goldmark-lint/releases/download/v#{version}/goldmark-lint_linux_arm64.tar.gz"
      sha256 "6faa7c2407943cc9985d6a09c7fec3dc3a98eaf21cbf06bbe6fbbff39e5a1bdb"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/goldmark-lint"]
    end
  end

  # No zap stanza required
end
