# This file was generated by GoReleaser. DO NOT EDIT.
cask "goldmark-lint" do
  name "goldmark-lint"
  desc "A Markdown linter written in Go using the goldmark parser"
  homepage "https://github.com/mrueg/goldmark-lint"
  version "0.2.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "goldmark-lint"

  on_macos do
    on_intel do
      url "https://github.com/mrueg/goldmark-lint/releases/download/v#{version}/goldmark-lint_darwin_amd64.tar.gz"
      sha256 "8c9e63d361b115551d518f62014799c927711496487636325c1ff0fa86df6068"
    end
    on_arm do
      url "https://github.com/mrueg/goldmark-lint/releases/download/v#{version}/goldmark-lint_darwin_arm64.tar.gz"
      sha256 "4cfb1dbaff9f2a4f1ef77f60f809617ec8aa21f5a289503f17430fbe6571990b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/mrueg/goldmark-lint/releases/download/v#{version}/goldmark-lint_linux_amd64.tar.gz"
      sha256 "e783a90229671f61fae88ed7b0e8c07ab30e9eb5c31a9bd9ccd6b10449098006"
    end
    on_arm do
      url "https://github.com/mrueg/goldmark-lint/releases/download/v#{version}/goldmark-lint_linux_arm64.tar.gz"
      sha256 "c584541eff8ca7c3f06debb835adb3d18aa82b1ca1595662945b21f13f3b8828"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/goldmark-lint"]
    end
  end

  # No zap stanza required
end
