# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoldmarkLint < Formula
  desc "A Markdown linter written in Go using the goldmark parser"
  homepage "https://github.com/mrueg/goldmark-lint"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrueg/goldmark-lint/releases/download/v0.2.2/goldmark-lint_darwin_amd64.tar.gz"
      sha256 "8e0dfd238e9d057f11f94db43552017e545b718453190253dd0f3b1710d0ac5c"

      define_method(:install) do
        bin.install "goldmark-lint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrueg/goldmark-lint/releases/download/v0.2.2/goldmark-lint_darwin_arm64.tar.gz"
      sha256 "3f5ea333746375629f71a15c4c2d7dc8c14b5428c53d76ea7f2ffd7ccfe7562e"

      define_method(:install) do
        bin.install "goldmark-lint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrueg/goldmark-lint/releases/download/v0.2.2/goldmark-lint_linux_amd64.tar.gz"
      sha256 "3febbd682b1b6d5b9b8245774aa3ff93c119034d3c67ad65ab200587041a83cc"
      define_method(:install) do
        bin.install "goldmark-lint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrueg/goldmark-lint/releases/download/v0.2.2/goldmark-lint_linux_arm64.tar.gz"
      sha256 "a3295b0545280ef193cc6e4ceb15020dcf629ab2b2888e416305c6250b1b9dfc"
      define_method(:install) do
        bin.install "goldmark-lint"
      end
    end
  end
end
