# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class GoldmarkLint < Formula
  desc "A Markdown linter written in Go using the goldmark parser"
  homepage "https://github.com/mrueg/goldmark-lint"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrueg/goldmark-lint/releases/download/v0.2.1/goldmark-lint_darwin_amd64.tar.gz"
      sha256 "e9f9957dc15a209fb75387ad7dc58b60796a2421b265b35b67837115748a2af5"

      define_method(:install) do
        bin.install "goldmark-lint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrueg/goldmark-lint/releases/download/v0.2.1/goldmark-lint_darwin_arm64.tar.gz"
      sha256 "872aee69e21f805d0dcd1857d3a8dd345c9eeb263af903adda13ffd86ca3047c"

      define_method(:install) do
        bin.install "goldmark-lint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrueg/goldmark-lint/releases/download/v0.2.1/goldmark-lint_linux_amd64.tar.gz"
      sha256 "cffa5f0b4dc55263c45174e9137acf756973bae6e2f5afb1b3fe877e3d64e1e5"
      define_method(:install) do
        bin.install "goldmark-lint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mrueg/goldmark-lint/releases/download/v0.2.1/goldmark-lint_linux_arm64.tar.gz"
      sha256 "b29a0b10afb98c870450513bcf12ec7d52d2496feacc6b1aee6da29f8dc8cd75"
      define_method(:install) do
        bin.install "goldmark-lint"
      end
    end
  end
end
