# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mmd < Formula
  desc "CLI tool to create mermaid diagrams"
  homepage "https://github.com/mrueg/go-mermaid"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrueg/go-mermaid/releases/download/v0.1.0/mmd_Darwin_x86_64.tar.gz"
      sha256 "c989b561b5da96403a030a4b226e7b2e9bbe419abc3c7b9090946a3377af2d5b"

      def install
        bin.install "mmd"
        generate_completions_from_executable(bin/"mmd", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrueg/go-mermaid/releases/download/v0.1.0/mmd_Darwin_arm64.tar.gz"
      sha256 "6120f1e217f7954714ce11b2b60cde74b924e37a67a50ea49b4e7e55c1fede6f"

      def install
        bin.install "mmd"
        generate_completions_from_executable(bin/"mmd", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/mrueg/go-mermaid/releases/download/v0.1.0/mmd_Linux_x86_64.tar.gz"
      sha256 "3f58d3041b82e1c9e6e69a0d2cb0450bad6874aa89574cdbd1c439131b7c5010"
      def install
        bin.install "mmd"
        generate_completions_from_executable(bin/"mmd", "completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/mrueg/go-mermaid/releases/download/v0.1.0/mmd_Linux_arm64.tar.gz"
      sha256 "6bc44c1036a6c2d639d835557045a91b07a664fac1dc3e0067060c4d566f0f35"
      def install
        bin.install "mmd"
        generate_completions_from_executable(bin/"mmd", "completion")
      end
    end
  end

  test do
    system "#{bin}/mmd", "version"
  end
end
