# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Owm < Formula
  desc "Library and CLI tool to create Wardley Maps"
  homepage "https://github.com/mrueg/go-wardley"
  version "0.1.3"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrueg/go-wardley/releases/download/v0.1.3/owm_Darwin_x86_64.tar.gz"
      sha256 "b8be2c502872b4a3f89990dacebd066a612c208cdb981091484bcc5e82f69648"

      def install
        bin.install "owm"
        generate_completions_from_executable(bin/"owm", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrueg/go-wardley/releases/download/v0.1.3/owm_Darwin_arm64.tar.gz"
      sha256 "f0a858aa0d66e4c0edabdbd3b14547fb29790ae2961a3646cfdd5d900213cd9c"

      def install
        bin.install "owm"
        generate_completions_from_executable(bin/"owm", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/mrueg/go-wardley/releases/download/v0.1.3/owm_Linux_x86_64.tar.gz"
      sha256 "b224dba9ae2e34d08e51fc52120104e3f23c8ac3d826e730d4d349dd56ea5321"
      def install
        bin.install "owm"
        generate_completions_from_executable(bin/"owm", "completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/mrueg/go-wardley/releases/download/v0.1.3/owm_Linux_arm64.tar.gz"
      sha256 "2fd409b96f9eff7919917d04e4813522817c26b81354a1d1216a6b8ac884ee8e"
      def install
        bin.install "owm"
        generate_completions_from_executable(bin/"owm", "completion")
      end
    end
  end

  test do
    system "#{bin}/owm", "version"
  end
end
