# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Owm < Formula
  desc "Library and CLI tool to create Wardley Maps"
  homepage "https://github.com/mrueg/go-wardley"
  version "0.1.1"
  license "Apache 2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mrueg/go-wardley/releases/download/v0.1.1/owm_Darwin_x86_64.tar.gz"
      sha256 "b1b86a93b8304b3ccd7512a27241d3701e7a6ae7a90332de7a4dbc33925179ec"

      def install
        bin.install "owm"
        generate_completions_from_executable(bin/"owm", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mrueg/go-wardley/releases/download/v0.1.1/owm_Darwin_arm64.tar.gz"
      sha256 "92d23966e5c421d5d26a7ce0be0e5fde54f7f2541d79ea1d7eebf5be92d214ce"

      def install
        bin.install "owm"
        generate_completions_from_executable(bin/"owm", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/mrueg/go-wardley/releases/download/v0.1.1/owm_Linux_x86_64.tar.gz"
      sha256 "272135002e7ee1ca2f0db456532d7ede9efd0e32d9868fa26e8ddb38c02b371b"
      def install
        bin.install "owm"
        generate_completions_from_executable(bin/"owm", "completion")
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/mrueg/go-wardley/releases/download/v0.1.1/owm_Linux_arm64.tar.gz"
      sha256 "dbf51440d6eb9c4be6f1c8d2f3868c555ae83fb7357e852a5a02519e48303d6c"
      def install
        bin.install "owm"
        generate_completions_from_executable(bin/"owm", "completion")
      end
    end
  end

  test do
    system "#{bin}/owm", "version"
  end
end
